server:
  port: ${SERVER_PORT:8551}

spring:
  application:
    name: admin-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

dynamodb:
  region: ${AWS_REGION}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

aws:
  s3:
    region: ${AWS_REGION}
    bucket-name: ${S3_BUCKET_NAME}

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1s
